spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookticket
    username: root
    password: 270701
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: vuhuyhung17062002@gmail.com
    password: skwk jbiz qydz gqsc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "YlYC92Q2NQlTEWXqxCMLhICbRb561RUicb+iEvw2sOTdWNOUavYJorDKyItY+0awM6rExXLQuDDCImefylr/wYQdTksaXc0mpJkQcg87vys="
#  valid-duration: 86400 # in second
#  refreshable-duration: 259200 # in seconds
  valid-duration: 1
  refreshable-duration: 2

outbound:
  identity:
    client-id: "775410551685-o7gobv3nm7054en071ef17il3hdnsho8.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000/authenticate"

vnpay:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/payments/vnpay/callback
  ipn-url: https://b8d0aa68f709.ngrok-free.app/payments/vnpay/ipn
  tmn-code: RTZSTG9H
  secret-key: 2AZN4DDW57TB4Q4OS8A50XQTCR625BAT
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

# Frontend URL
frontend:
  url: "http://localhost:3000"
