spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookticket
    username: root
    password: Huu@123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "YlYC92Q2NQlTEWXqxCMLhICbRb561RUicb+iEvw2sOTdWNOUavYJorDKyItY+0awM6rExXLQuDDCImefylr/wYQdTksaXc0mpJkQcg87vys="
#  valid-duration: 86400 # in second
#  refreshable-duration: 259200 # in seconds
  valid-duration: 1
  refreshable-duration: 2

vnpay:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/payments/vnpay/callback
  ipn-url: https://b8d0aa68f709.ngrok-free.app/payments/vnpay/ipn
  tmn-code: RTZSTG9H
  secret-key: 2AZN4DDW57TB4Q4OS8A50XQTCR625BAT
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

# Frontend URL
frontend:
  url: "http://localhost:3000"
